### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by sarahy004** [evanmcc1/CMSC447-Project#3]
Need Feedback when ready. Will be posted either here or in hangouts.

**Comment by KevinRapa** [comment]
![676019632-612x612](https://user-images.githubusercontent.com/23650177/45851107-1cc6a000-bd07-11e8-9448-599d37573ef8.jpg)

Can we use this or a variation of this?

**Comment by huganir1** [comment]
The logo with transparency is in the webpage folder under image
